name: Github JD-sign bot

on:
    push:
        branches:
            - master
    workflow_dispatch: # 手动触发
    schedule:
        - cron: '10 16 * * *'
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
              with:
                ref: 'master'
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: Cache cookies
              uses: actions/cache@v2
              with:
                path: ~/cookies.json
                key: ${{ secrets.CACHE_NAME }}-${{ github.run_id }}
                restore-keys: ${{ secrets.CACHE_NAME }}-
            - name: Run app
              run: npm install
            - name: Run app.js
              env:
                JD_COOKIE: ${{ secrets.JD_COOKIE }}
                JD_COOKIE_2: ${{ secrets.JD_COOKIE_2 }} 
                PUSH_KEY: ${{ secrets.PUSH_KEY }}
              run: |
                  if [ -e ~/cookies.json ]; then cp ~/cookies.json cookies.json; fi
                  node update_cookie.js
                  if [ -e cookies.json ]; then cp cookies.json ~/cookies.json; fi
                  JD_COOKIE="$(cat cookies_str.txt)" node app.js
                  cat result.txt
